//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Auditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المراجع الذكي.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Login {
            get {
                object obj = ResourceManager.GetObject("Login", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MainBackground {
            get {
                object obj = ResourceManager.GetObject("MainBackground", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حفظ الإعدادات بنجاح.
        /// </summary>
        internal static string MsgAppSettingsSaved {
            get {
                return ResourceManager.GetString("MsgAppSettingsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة بيانات المقاول بنجاح.
        /// </summary>
        internal static string MsgContractorAdded {
            get {
                return ResourceManager.GetString("MsgContractorAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل ترغب حقاً في حذف بيانات المقاول الحالي؟.
        /// </summary>
        internal static string MsgContractorDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgContractorDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات المقاول بنجاح.
        /// </summary>
        internal static string MsgContractordeleted {
            get {
                return ResourceManager.GetString("MsgContractordeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات المقاول بنجاح.
        /// </summary>
        internal static string MsgContractorUpdated {
            get {
                return ResourceManager.GetString("MsgContractorUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة بيانات المستند بنجاح.
        /// </summary>
        internal static string MsgDocumentAdded {
            get {
                return ResourceManager.GetString("MsgDocumentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تود حقاً حذف بيانات هذا المستند؟.
        /// </summary>
        internal static string MsgDocumentDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDocumentDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات المستند بنجاح.
        /// </summary>
        internal static string MsgDocumentDeleted {
            get {
                return ResourceManager.GetString("MsgDocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات المستند بنجاح.
        /// </summary>
        internal static string MsgDocumentUpdated {
            get {
                return ResourceManager.GetString("MsgDocumentUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات الموظف بنجاح.
        /// </summary>
        internal static string MsgEmloyeeDeleted {
            get {
                return ResourceManager.GetString("MsgEmloyeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة بيانات الموظف بنجاح.
        /// </summary>
        internal static string MsgEmployeeAdded {
            get {
                return ResourceManager.GetString("MsgEmployeeAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل ترغب حقاً في حذف بيانات هذا الموظف؟.
        /// </summary>
        internal static string MsgEmployeeDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgEmployeeDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تود حقاً حذف بيانات الموظف من هذا المستند؟.
        /// </summary>
        internal static string MsgEmployeeTransFeeDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgEmployeeTransFeeDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات الموظف من المستند بنجاح.
        /// </summary>
        internal static string MsgEmployeeTransFeeDeleted {
            get {
                return ResourceManager.GetString("MsgEmployeeTransFeeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات الموظف بنجاح.
        /// </summary>
        internal static string MsgEmployeeUpdated {
            get {
                return ResourceManager.GetString("MsgEmployeeUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة بيانات جهة العمل بنجاح.
        /// </summary>
        internal static string MsgLocationAdded {
            get {
                return ResourceManager.GetString("MsgLocationAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تود حقاً حذف بيانات جهة العمل الحالية؟.
        /// </summary>
        internal static string MsgLocationDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgLocationDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات جهة العمل الحالية بنجاح.
        /// </summary>
        internal static string MsgLocationDeleted {
            get {
                return ResourceManager.GetString("MsgLocationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات جهة العمل بنجاح.
        /// </summary>
        internal static string MsgLocationUpdated {
            get {
                return ResourceManager.GetString("MsgLocationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيم المدخلة غير صحيحة برجاء إدخال قيم رقمية.
        /// </summary>
        internal static string MsgMathException {
            get {
                return ResourceManager.GetString("MsgMathException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البيانات المدخلة غير صحيحة تاريخ نهو الأعمال سابق لتاريخ بدء الأعمال.
        /// </summary>
        internal static string MsgProjectDatesInvalid {
            get {
                return ResourceManager.GetString("MsgProjectDatesInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عفواً لا يمكنك تشغيل أكثر من نسخة من البرنامج.
        /// </summary>
        internal static string MsgSingleInstance {
            get {
                return ResourceManager.GetString("MsgSingleInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة بيانات المستخدم بنجاح.
        /// </summary>
        internal static string MsgUserAdded {
            get {
                return ResourceManager.GetString("MsgUserAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متأكد أنك تريد حذف بيانات هذا المستخدم؟.
        /// </summary>
        internal static string MsgUserDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgUserDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات المستخدم بنجاح.
        /// </summary>
        internal static string MsgUserDeleted {
            get {
                return ResourceManager.GetString("MsgUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تمت إضافة بيانات مجموعة المستخدمين بنجاح.
        /// </summary>
        internal static string MsgUserGroupAdded {
            get {
                return ResourceManager.GetString("MsgUserGroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تود حقاً حذف بيانات مجموعة المستخدمين الحالية؟.
        /// </summary>
        internal static string msgUserGroupDeleteConfirm {
            get {
                return ResourceManager.GetString("msgUserGroupDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف بيانات مجموعة المستخدمين الحالية بنجاح.
        /// </summary>
        internal static string MsgUserGroupDeleted {
            get {
                return ResourceManager.GetString("MsgUserGroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات مجموعة المستخدمين بنجاح.
        /// </summary>
        internal static string MsgUserGroupUpdated {
            get {
                return ResourceManager.GetString("MsgUserGroupUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تحديث بيانات المستخدم بنجاح.
        /// </summary>
        internal static string MsgUserUpdated {
            get {
                return ResourceManager.GetString("MsgUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الرد.
        /// </summary>
        internal static string StringStatuesReserved {
            get {
                return ResourceManager.GetString("StringStatuesReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Zero {
            get {
                return ResourceManager.GetString("Zero", resourceCulture);
            }
        }
    }
}
